import { generatePlayerPool, generateReplacementPlayer } from './generator';
import { MatchResult, simulateMatch } from './matchSim';
import {
  FORMATIONS,
  GameConfig,
  Player,
  Team,
  TeamId,
  assignToSquad,
  emptySquad,
  openSlotsForPosition,
} from './types';

export type Phase = 'setup' | 'ready' | 'bidding' | 'auctionResult' | 'suspense' | 'matchSim' | 'gameOver';

export type AuctionResultInfo =
  | {
      type: 'won';
      player: Player;
      winner: TeamId;
      amount: number;
      contested: boolean;
      /**
       * True only when this player never passed through BiddingScreen (the
       * revealNext single-eligible-team shortcut) - the result screen needs
       * to do the reveal flip itself in that case. Every other win (auction,
       * draft, sealed) was already flipped face-up in BiddingScreen, however
       * `contested` shakes out for that mode.
       */
      freshReveal: boolean;
      /** Present only for sealed-bid wins, so the result screen can reveal both secret bids. */
      sealedBids?: Record<TeamId, number>;
      /** Present only in draft mode when the winner got this player because the other side passed. */
      draftPassed?: boolean;
    }
  | { type: 'skipped'; player: Player; replacement: Player };

export interface GameState {
  phase: Phase;
  config: GameConfig;
  pool: Player[];
  /** Pool size at game start - used to show "X of Y players auctioned" progress. */
  totalPlayers: number;
  currentPlayer: Player | null;
  teams: Record<TeamId, Team>;
  startingBidder: TeamId;
  currentBid: number;
  currentBidder: TeamId | null;
  turn: TeamId | null;
  /** Whether the first team to act this auction has already passed without placing a bid. */
  openingPassed: boolean;
  /** Sealed-bid mode only: each side's secret bid for the current player, or null before/game not in sealed mode. */
  sealedBids: Record<TeamId, number | null> | null;
  matchResult: MatchResult | null;
  lastResult: AuctionResultInfo | null;
}

export type GameAction =
  | { type: 'START_GAME'; config: GameConfig }
  | { type: 'REVEAL_NEXT' }
  | { type: 'RAISE' }
  | { type: 'BID_CUSTOM'; amount: number }
  | { type: 'PASS' }
  | { type: 'DRAFT_TAKE' }
  | { type: 'SUBMIT_SEALED_BID'; amount: number }
  | { type: 'CONTINUE_AFTER_RESULT' }
  | { type: 'FINISH_SUSPENSE' }
  | { type: 'FINISH_MATCH_SIM' }
  | { type: 'RESET' };

function otherTeam(team: TeamId): TeamId {
  return team === 1 ? 2 : 1;
}

/**
 * Teams that could actually take part in an auction for this player: they
 * need an open slot for the position, and - outside draft mode, which is
 * free - enough budget to place the opening bid. Without the budget check,
 * two broke teams would pass forever on every same-position replacement
 * generated by resolveSkip, since neither could ever bid: a permanent stall
 * the pool would never drain out of.
 */
function eligibleTeams(teams: Record<TeamId, Team>, player: Player, config: GameConfig): TeamId[] {
  const needsBudget = config.biddingMode !== 'draft';
  const result: TeamId[] = [];
  ([1, 2] as TeamId[]).forEach((id) => {
    const hasSlot = openSlotsForPosition(teams[id].squad, player.position) > 0;
    const canAfford = !needsBudget || teams[id].budget >= config.bidIncrement;
    if (hasSlot && canAfford) result.push(id);
  });
  return result;
}

export function initialState(): GameState {
  const formation = FORMATIONS.classic.requirements;
  return {
    phase: 'setup',
    config: {
      startingBudget: 100,
      bidIncrement: 5,
      team1Name: 'Player 1',
      team2Name: 'Player 2',
      team1Avatar: 'flame',
      team2Avatar: 'shield',
      hideRatings: false,
      biddingMode: 'auction',
      playerPool: 'all',
      endMode: 'ovr',
      formation: 'classic',
      timerSeconds: null,
    },
    pool: [],
    totalPlayers: 0,
    currentPlayer: null,
    teams: {
      1: { name: 'Player 1', budget: 100, squad: emptySquad(formation), avatar: 'flame' },
      2: { name: 'Player 2', budget: 100, squad: emptySquad(formation), avatar: 'shield' },
    },
    startingBidder: 1,
    currentBid: 0,
    currentBidder: null,
    turn: null,
    openingPassed: false,
    sealedBids: null,
    matchResult: null,
    lastResult: null,
  };
}

function resolveWin(
  state: GameState,
  winner: TeamId,
  amount: number,
  contested: boolean,
  freshReveal: boolean
): GameState {
  const player = state.currentPlayer!;
  const winningTeam = state.teams[winner];
  const clampedAmount = Math.min(amount, winningTeam.budget);

  const updatedTeam: Team = {
    ...winningTeam,
    budget: winningTeam.budget - clampedAmount,
    squad: assignToSquad(winningTeam.squad, player),
  };

  return {
    ...state,
    phase: 'auctionResult',
    teams: { ...state.teams, [winner]: updatedTeam },
    currentPlayer: null,
    currentBid: 0,
    currentBidder: null,
    turn: null,
    openingPassed: false,
    sealedBids: null,
    startingBidder: otherTeam(state.startingBidder),
    lastResult: { type: 'won', player, winner, amount: clampedAmount, contested, freshReveal },
  };
}

/** Both sides declined to bid at all: discard the player and queue a same-position replacement. */
function resolveSkip(state: GameState): GameState {
  const player = state.currentPlayer!;
  const replacement = generateReplacementPlayer(player.position, state.config.playerPool);
  return {
    ...state,
    phase: 'auctionResult',
    currentPlayer: null,
    currentBid: 0,
    currentBidder: null,
    turn: null,
    openingPassed: false,
    sealedBids: null,
    startingBidder: otherTeam(state.startingBidder),
    pool: [replacement, ...state.pool],
    lastResult: { type: 'skipped', player, replacement },
  };
}

/** Resolves a completed pair of sealed bids into a win or a mutual-skip. */
function resolveSealedRound(state: GameState, bids: Record<TeamId, number>): GameState {
  const bid1 = bids[1];
  const bid2 = bids[2];

  if (bid1 === 0 && bid2 === 0) {
    return resolveSkip(state);
  }

  let winner: TeamId;
  let amount: number;
  let contested: boolean;
  if (bid1 === bid2) {
    // Tie on a genuine bid (not 0-0, handled above): resolved deterministically
    // in favor of this round's starting bidder rather than a re-bid.
    winner = state.startingBidder;
    amount = bid1;
    contested = true;
  } else if (bid1 > bid2) {
    winner = 1;
    amount = bid1;
    contested = bid2 > 0;
  } else {
    winner = 2;
    amount = bid2;
    contested = bid1 > 0;
  }

  // Already flipped face-up in BiddingScreen before either side bid.
  const resolved = resolveWin(state, winner, amount, contested, false);
  return {
    ...resolved,
    lastResult:
      resolved.lastResult && resolved.lastResult.type === 'won'
        ? { ...resolved.lastResult, sealedBids: { 1: bid1, 2: bid2 } }
        : resolved.lastResult,
  };
}

/**
 * Pops the next player from the pool and either starts a contested auction or
 * auto-resolves an uncontested one. Shared by REVEAL_NEXT and by START_GAME
 * (which reveals round 1 immediately, skipping the "ready" tap screen).
 */
function revealNext(state: GameState): GameState {
  if (state.pool.length === 0) {
    return { ...state, phase: 'suspense' };
  }
  const [next, ...rest] = state.pool;
  const eligible = eligibleTeams(state.teams, next, state.config);

  if (eligible.length === 0) {
    // Nobody has both an open slot and enough budget to bid - discard and
    // move on rather than starting an auction neither side could ever win.
    return revealNext({ ...state, pool: rest });
  }

  if (eligible.length === 1) {
    // This player never visited BiddingScreen at all, so the result screen
    // needs to do the reveal flip itself.
    return resolveWin(
      { ...state, pool: rest, currentPlayer: next },
      eligible[0],
      state.config.biddingMode === 'draft' ? 0 : state.config.bidIncrement,
      false,
      true
    );
  }

  return {
    ...state,
    pool: rest,
    currentPlayer: next,
    phase: 'bidding',
    currentBid: 0,
    currentBidder: null,
    turn: state.startingBidder,
    openingPassed: false,
    sealedBids: state.config.biddingMode === 'sealed' ? { 1: null, 2: null } : null,
  };
}

export function gameReducer(state: GameState, action: GameAction): GameState {
  switch (action.type) {
    case 'START_GAME': {
      const { config } = action;
      const requirements = FORMATIONS[config.formation].requirements;
      const pool = generatePlayerPool(requirements, config.playerPool);
      const freshState: GameState = {
        ...initialState(),
        config,
        pool,
        totalPlayers: pool.length,
        teams: {
          1: {
            name: config.team1Name || 'Player 1',
            budget: config.startingBudget,
            squad: emptySquad(requirements),
            avatar: config.team1Avatar,
          },
          2: {
            name: config.team2Name || 'Player 2',
            budget: config.startingBudget,
            squad: emptySquad(requirements),
            avatar: config.team2Avatar,
          },
        },
      };
      // Round 1 skips the "ready" tap screen and reveals immediately.
      return revealNext(freshState);
    }

    case 'REVEAL_NEXT':
      return revealNext(state);

    case 'RAISE': {
      if (state.phase !== 'bidding' || state.turn === null || state.config.biddingMode !== 'auction') {
        return state;
      }
      const raiser = state.turn;
      const newBid = state.currentBid + state.config.bidIncrement;
      if (newBid > state.teams[raiser].budget) return state; // can't afford, ignore
      return {
        ...state,
        currentBid: newBid,
        currentBidder: raiser,
        turn: otherTeam(raiser),
      };
    }

    case 'BID_CUSTOM': {
      if (state.phase !== 'bidding' || state.turn === null || state.config.biddingMode !== 'auction') {
        return state;
      }
      const raiser = state.turn;
      const amount = Math.floor(action.amount);
      const minValid = state.currentBidder === null ? state.config.bidIncrement : state.currentBid + 1;
      if (!Number.isFinite(amount) || amount < minValid || amount > state.teams[raiser].budget) {
        return state; // invalid, ignore (UI is expected to validate before dispatching)
      }
      return {
        ...state,
        currentBid: amount,
        currentBidder: raiser,
        turn: otherTeam(raiser),
      };
    }

    case 'PASS': {
      if (state.phase !== 'bidding' || state.turn === null) return state;
      if (state.config.biddingMode === 'sealed') return state; // sealed mode uses SUBMIT_SEALED_BID

      if (state.config.biddingMode === 'draft') {
        // Draft mode has no true "skip" - if this side doesn't want the
        // player, the other side gets them for free instead. revealNext only
        // enters bidding with two eligible teams, so the other side is
        // guaranteed to have an open slot for them.
        const otherId = otherTeam(state.turn);
        const resolved = resolveWin(state, otherId, 0, false, false);
        return {
          ...resolved,
          lastResult:
            resolved.lastResult && resolved.lastResult.type === 'won'
              ? { ...resolved.lastResult, draftPassed: true }
              : resolved.lastResult,
        };
      }

      // Auction mode - already flipped face-up in BiddingScreen.
      if (state.currentBidder !== null) {
        return resolveWin(state, state.currentBidder, state.currentBid, true, false);
      }
      if (!state.openingPassed) {
        return { ...state, turn: otherTeam(state.turn), openingPassed: true };
      }
      return resolveSkip(state);
    }

    case 'DRAFT_TAKE': {
      if (state.phase !== 'bidding' || state.turn === null || state.config.biddingMode !== 'draft') {
        return state;
      }
      // Already flipped face-up in BiddingScreen before this decision.
      return resolveWin(state, state.turn, 0, false, false);
    }

    case 'SUBMIT_SEALED_BID': {
      if (
        state.phase !== 'bidding' ||
        state.turn === null ||
        state.config.biddingMode !== 'sealed' ||
        !state.sealedBids
      ) {
        return state;
      }
      const bidder = state.turn;
      const amount = Math.floor(action.amount);
      const isPass = amount === 0;
      const isValidBid = amount >= state.config.bidIncrement && amount <= state.teams[bidder].budget;
      if (!Number.isFinite(amount) || amount < 0 || !(isPass || isValidBid)) {
        return state; // invalid, ignore (UI is expected to validate before dispatching)
      }

      const newBids = { ...state.sealedBids, [bidder]: amount };
      const otherId = otherTeam(bidder);
      if (newBids[otherId] === null) {
        // Still waiting on the other side - hand off without resolving or
        // revealing this bid.
        return { ...state, sealedBids: newBids, turn: otherId };
      }
      return resolveSealedRound(state, newBids as Record<TeamId, number>);
    }

    case 'CONTINUE_AFTER_RESULT': {
      if (state.pool.length === 0) {
        return { ...state, phase: 'suspense', lastResult: null };
      }
      return { ...state, phase: 'ready', lastResult: null };
    }

    case 'FINISH_SUSPENSE': {
      if (state.phase !== 'suspense') return state;
      if (state.config.endMode === 'matchSim') {
        const matchResult = simulateMatch(state.teams[1], state.teams[2]);
        return { ...state, phase: 'matchSim', matchResult };
      }
      return { ...state, phase: 'gameOver' };
    }

    case 'FINISH_MATCH_SIM': {
      if (state.phase !== 'matchSim') return state;
      return { ...state, phase: 'gameOver' };
    }

    case 'RESET':
      return initialState();

    default:
      return state;
  }
}
