import { ImageSourcePropType } from 'react-native';

/**
 * Real photos for curated Icon players, keyed by their exact Player.name.
 * Metro requires static string literals for asset requires, so this map is
 * spelled out explicitly rather than derived from a slugified name.
 */
export const ICON_PHOTOS: Record<string, ImageSourcePropType> = {
  'Lev Yashin': require('../assets/players/lev-yashin.jpg'),
  'Gianluigi Buffon': require('../assets/players/gianluigi-buffon.jpg'),
  'Iker Casillas': require('../assets/players/iker-casillas.jpg'),
  'Peter Schmeichel': require('../assets/players/peter-schmeichel.jpg'),
  'Manuel Neuer': require('../assets/players/manuel-neuer.jpg'),
  'Thibaut Courtois': require('../assets/players/thibaut-courtois.jpg'),
  'Alisson Becker': require('../assets/players/allison-becker.jpg'),
  Ederson: require('../assets/players/ederson.jpg'),
  'David de Gea': require('../assets/players/david-de-gea.jpg'),
  'Petr Cech': require('../assets/players/petr-cech.jpg'),
  'Marc-Andre ter Stegen': require('../assets/players/marc-andre-ter-stegen.jpg'),
  'Jordan Pickford': require('../assets/players/jordan-pickford.jpg'),

  'Franz Beckenbauer': require('../assets/players/franz-beckenbauer.jpg'),
  'Paolo Maldini': require('../assets/players/paolo-maldini.jpg'),
  'Fabio Cannavaro': require('../assets/players/fiabo-cannavaro.jpg'),
  'Bobby Moore': require('../assets/players/bobby-moore.jpg'),
  'Sergio Ramos': require('../assets/players/sergio-ramos.jpg'),
  'Virgil van Dijk': require('../assets/players/virgil-van-dijk.jpg'),
  Marcelo: require('../assets/players/marcelo.jpg'),
  'Dani Alves': require('../assets/players/dani-alves.jpg'),
  'Thiago Silva': require('../assets/players/thiago-silva.jpg'),
  'Kalidou Koulibaly': require('../assets/players/kalidou-koulibaly.jpg'),
  'Trent Alexander-Arnold': require('../assets/players/trent-alexander-arnold.jpg'),
  'Andrew Robertson': require('../assets/players/andrew-robertson.jpg'),
  'Ruben Dias': require('../assets/players/ruben-dias.jpg'),
  'Kyle Walker': require('../assets/players/kyle-walker.jpg'),
  'Vincent Kompany': require('../assets/players/vincent-kompany.jpg'),
  'Gerard Pique': require('../assets/players/gerard-pique.jpg'),
  'Carles Puyol': require('../assets/players/carles-puyol.jpg'),
  'William Saliba': require('../assets/players/william-saliba.jpg'),
  'Harry Maguire': require('../assets/players/harry-maguire.jpg'),
  'John Arne Riise': require('../assets/players/john-arne-riise.jpg'),

  'Zinedine Zidane': require('../assets/players/zinedine-zidane.jpg'),
  'Johan Cruyff': require('../assets/players/johan-cruyff.jpg'),
  'Diego Maradona': require('../assets/players/diego-maradona.jpg'),
  'Xavi Hernandez': require('../assets/players/xavi-hernandez.jpg'),
  'Andrea Pirlo': require('../assets/players/andrea-pirlo.jpg'),
  'Kevin De Bruyne': require('../assets/players/kevin-de-bruyne.jpg'),
  'Luka Modric': require('../assets/players/luka-modric.jpg'),
  'Andres Iniesta': require('../assets/players/andres-iniesta.jpg'),
  'Toni Kroos': require('../assets/players/toni-kroos.jpg'),
  "N'Golo Kante": require("../assets/players/n'golo-kante.jpg"),
  'Frenkie de Jong': require('../assets/players/frenkie-de-jong.jpg'),
  'Bruno Fernandes': require('../assets/players/bruno-fernandes.jpg'),
  'Paul Pogba': require('../assets/players/paul-pogba.jpg'),
  Kaka: require('../assets/players/kaka.jpg'),
  Ronaldinho: require('../assets/players/ronaldinho.jpg'),
  'Steven Gerrard': require('../assets/players/steven-gerrard.jpg'),
  'Jordan Henderson': require('../assets/players/jordan-henderson.jpg'),
  Fabinho: require('../assets/players/fabinho.jpg'),
  'Thiago Alcantara': require('../assets/players/thiago-alcantara.jpg'),
  'David Silva': require('../assets/players/david-silva.jpg'),
  'Yaya Toure': require('../assets/players/yaya-toure.jpg'),
  Rodri: require('../assets/players/rodri.jpg'),
  'Bernardo Silva': require('../assets/players/bernardo-silva.jpg'),
  'Sergio Busquets': require('../assets/players/sergio-busquets.jpg'),
  Pedri: require('../assets/players/pedri.jpg'),
  'Declan Rice': require('../assets/players/declan-rice.jpg'),
  'Joshua Kimmich': require('../assets/players/joshua-kimmich.jpg'),
  Sam: require('../assets/players/samuel-faith-karengera.jpg'),

  Pele: require('../assets/players/pele.jpg'),
  'Ronaldo Nazario': require('../assets/players/ronaldo-nazario.jpg'),
  'Marco van Basten': require('../assets/players/marco-van-basten.jpg'),
  'Gerd Muller': require('../assets/players/gerd-muller.jpg'),
  Eusebio: require('../assets/players/eusebio.jpg'),
  'Lionel Messi': require('../assets/players/lionel-messi.jpg'),
  'Cristiano Ronaldo': require('../assets/players/cristiano-ronaldo.jpg'),
  'Neymar Jr': require('../assets/players/neymar-jr.jpg'),
  'Mohamed Salah': require('../assets/players/mohamed-salah.jpg'),
  'Sadio Mane': require('../assets/players/sadio-mane.jpg'),
  'Romelu Lukaku': require('../assets/players/romelu-lukaku.jpg'),
  'Robert Lewandowski': require('../assets/players/robert-lewandowski.jpg'),
  'Erling Haaland': require('../assets/players/erling-haaland.jpg'),
  'Kylian Mbappe': require('../assets/players/kylian-mbappe.jpg'),
  'Harry Kane': require('../assets/players/harry-kane.jpg'),
  'Luis Suarez': require('../assets/players/luis-suarez.jpg'),
  'Sergio Aguero': require('../assets/players/sergio-aguero.jpg'),
  'Roberto Firmino': require('../assets/players/robert-firmino.jpg'),
  'Riyad Mahrez': require('../assets/players/riyad-mahrez.jpg'),
  'Antoine Griezmann': require('../assets/players/antoine-griezmann.jpg'),
  'Bukayo Saka': require('../assets/players/bukayo-saka.jpg'),
  'Son Heung-min': require('../assets/players/son-heung-min.jpg'),
  'Cole Palmer': require('../assets/players/cole-palmer.jpg'),
  'Marcus Rashford': require('../assets/players/marcus-rashford.jpg'),
  'Ian Rush': require('../assets/players/ian-rush.jpg'),
  'Kevin Karengera': require('../assets/players/kevin-karengera.jpg'),
};
